export const PAX_TYPES = ['Adult', 'Child', 'Infant'] as const;
export const GENDERS = ['Male', 'Female'] as const;
export const TRIP_TYPES = ['Oneway', 'Roundtrip'] as const;
export const CURRENCIES = ['USD', 'CAD'] as const;

export const CARD_TYPES = [
  'MASTER',
  'VISA',
  'VISA_DEBIT',
  'AMEX',
  'PAYPAL',
  'MASTER_DEBIT',
  'MESTRO',
  'DINERS',
  'DISCOVER',
] as const;

export const EXPIRY_MONTHS = [
  '01','02','03','04','05','06','07','08','09','10','11','12',
] as const;

export const EXPIRY_YEARS = Array.from({ length: 31 }, (_, i) =>
  String(2026 + i)
);

export const REASONS_OF_SALE = [
  'New Booking - HK',
  'Exchange',
  'Seat Assignments',
  'Upgrade',
  'New Booking - Fxl',
  'New Booking - Online',
  'Inhouse Re-Issue',
  'Baggage Addition',
  'Pet',
  'Insurance',
  'Hotel Booking',
  'Package - Flight + Hotel',
  'Name Correction',
  'Flight + Pet',
  'Car Hire',
  'Changes',
  'Exchange + New Booking',
] as const;

export const BOOKING_STATUSES = [
  'MCO Decline + Work Pending',
  'Cux CTC Merchant for clarification',
  'MCO Charged + Work Pending',
  'Need Sup Approval',
  'MCO VOIDED',
  'MCO REFUNDED',
  'RDR ALERT',
  'CB RECEIVED',
  'Docs Pending',
  'Verification Failure',
  'MCO CHARGED',
  'TKT + MCO CHARGED',
  'TKT DECLINE MCO CHARGED',
  'Cancel Due to Decline',
  'TKT ISS MCO DECLINE',
  'TKT + MCO Decline',
  'Decline for MILES',
  'Decline for HK',
  'Withdrawal limit Exceed',
  'Card Block',
  'Pick-Up Card',
  'AVS Failure',
  'Do Not Honor',
  'Insufficient Funds',
  'Follow Up',
  'Need Approval for TKT',
  'Need Approval for MCO',
  'Escalation',
  'Verbal Auth',
  'No Action taken by Agent',
  'WIP',
  'Missing Details',
  'Under Agent Follow up',
  'Under Follow up',
  'Exchange Not Permitted for Credit',
  'Exchange Not Permitted for Refund',
  'Seats not Available',
  'CCD on AL',
  'Changes Denied by AL',
  'Work Done',
  'Work Done Charge MCO',
  'Cux Cancellation',
  'Partial Refund',
  'Void',
  'Refund',
  'Re-Run',
  'CCD on AL, Hold MCO',
  'Issue HK + Charge MCO',
  'CCD on AL-Charge MCO',
  'Work Pending Charge MCO',
  'Miles Booking',
  'Mileage + Cash',
  'New Booking with Mileage',
  'Schedule Change',
  'New Booking with Upgrade',
  'Unable to Process Online',
  'Card Decline Online',
  'Pet Booking',
  'Booking Confirmation',
  'Seat Assignment',
  'New Booking',
  'Exchange with Credit',
  'Change',
  'Add Remarks',
] as const;