import React, { useEffect, useRef, useState } from 'react';
import { NavLink } from 'react-router-dom';
import { useAuth } from '../hooks/useAuth';
import { isAdminUser, loadUserPermission, normalizePath } from '../utils/permissions';

interface SidebarProps { isOpen: boolean; }
interface MenuItem { title: string; icon: React.ReactNode; path?: string; subItems?: { title: string; path: string }[]; }
const icon = (path: string) => <svg className="size-[18px] shrink-0" fill="none" stroke="currentColor" viewBox="0 0 24 24" aria-hidden="true"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.8} d={path} /></svg>;
const menuItems: MenuItem[] = [
  { title: 'Dashboard', path: '/dashboard', icon: icon('M3 12l2-2 7-7 7 7m-2-2v10a1 1 0 01-1 1h-3v-5H11v5H8a1 1 0 01-1-1V10') },
  { title: 'User Access Manager', icon: icon('M16 21v-2a4 4 0 00-4-4H6a4 4 0 00-4 4v2m7-8a4 4 0 100-8 4 4 0 000 8zm7-5a4 4 0 010 8m4 5v-2a4 4 0 00-3-3.87'), subItems: [{ title: 'Create User', path: '/users/create' }, { title: 'Create Role', path: '/users/roles' }, { title: 'Role & Permission', path: '/users/permissions' }] },
  { title: 'Manage Master', icon: icon('M4 7h16M4 12h16M4 17h16'), subItems: [{ title: 'Type of Booking', path: '/master/booking-types' }, { title: 'Currency Specification', path: '/master/currencies' }, { title: 'Charging Bifurcation', path: '/master/sources' }, { title: 'Card Type', path: '/master/card-types' }, { title: 'Email Template', path: '/master/email-templates' }, { title: 'Manage Sale Types', path: '/master/sale-types' }, { title: 'Assign Booking Status', path: '/master/assign-booking-status' }] },
  { title: 'Booking Management', icon: icon('M6 3v4m12-4v4M4 9h16M5 5h14a1 1 0 011 1v13a1 1 0 01-1 1H5a1 1 0 01-1-1V6a1 1 0 011-1z'), subItems: [{ title: 'All Bookings', path: '/bookings/all' }, { title: 'Add Booking', path: '/bookings/new' }, { title: 'Assignments', path: '/bookings/assignments' }, { title: 'Pending Holds', path: '/bookings/holds' }] },
  { title: 'IP Restrictions', icon: icon('M12 2l8 3v6c0 5-3.5 9.5-8 11-4.5-1.5-8-6-8-11V5l8-3zm-3 10l2 2 4-4'), subItems: [{ title: 'IP Restriction', path: '/users/ip-restriction' }] },
  { title: 'Break Tracker', icon: icon('M3 9a2 2 0 012-2h3l1-2h6l1 2h3a2 2 0 012 2v9a2 2 0 01-2 2H5a2 2 0 01-2-2V9zm9 2a3 3 0 100 6 3 3 0 000-6z'), subItems: [{ title: 'Activity Type', path: '/break-tracker/activity-type' }, { title: 'Break Tracker', path: '/break-tracker/tracker' }] },
  { title: 'Attendance System', icon: icon('M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z'), subItems: [{ title: 'Daily Logs', path: '/attendance/logs' }, { title: 'Summary', path: '/attendance/summary' }] },
];
const Sidebar: React.FC<SidebarProps> = ({ isOpen }) => {
  const { user } = useAuth(); const [openMenus, setOpenMenus] = useState<Record<string, boolean>>({ 'User Access Manager': true }); const [visibleMenuItems, setVisibleMenuItems] = useState<MenuItem[]>(menuItems); const [hovered, setHovered] = useState<string | null>(null); const [hoverTop, setHoverTop] = useState(0); const timer = useRef<ReturnType<typeof setTimeout> | null>(null);
  useEffect(() => { if (isAdminUser(user)) { setVisibleMenuItems(menuItems); return; } loadUserPermission(user).then((permissions) => { if (!permissions) return setVisibleMenuItems([]); setVisibleMenuItems(menuItems.flatMap(item => { if (item.title === 'Dashboard' && !permissions.dashboardAllowed) return []; if (!item.subItems) return [item]; const subItems = item.subItems.filter(sub => permissions.allowedPaths.has(normalizePath(sub.path))); return subItems.length ? [{ ...item, subItems }] : []; })); }).catch(() => setVisibleMenuItems([])); }, [user, user?.user_role]);
  const hide = () => { timer.current = setTimeout(() => setHovered(null), 150); }; const show = (title: string, top?: number) => { if (timer.current) clearTimeout(timer.current); if (top !== undefined) setHoverTop(top); setHovered(title); };
  return <aside className={`app-sidebar fixed left-0 top-[68px] bottom-0 z-40 overflow-y-auto bg-white ${isOpen ? 'w-[236px] sidebar-open' : 'w-[72px] sidebar-closed'}`}><div className="px-3 py-5"><p className={`sidebar-label px-3 pb-2 ${!isOpen ? 'sr-only' : ''}`}>Workspace</p><nav className="space-y-1">{visibleMenuItems.map(item => { const nested = Boolean(item.subItems?.length); const expanded = Boolean(openMenus[item.title]); return <div key={item.title} className="relative" onMouseEnter={e => !isOpen && show(item.title, e.currentTarget.getBoundingClientRect().top)} onMouseLeave={() => !isOpen && hide()}>{nested ? <button className={`app-nav-item w-full ${expanded ? 'is-open' : ''}`} onClick={() => setOpenMenus(old => ({ ...old, [item.title]: !old[item.title] }))}><span>{item.icon}</span>{isOpen && <><span className="truncate">{item.title}</span><svg className={`ml-auto size-3.5 transition-transform ${expanded ? 'rotate-180' : ''}`} fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeWidth="2" d="M6 9l6 6 6-6" /></svg></>}</button> : <NavLink to={item.path || '#'} className={({ isActive }) => `app-nav-item ${isActive ? 'active' : ''}`}><span>{item.icon}</span>{isOpen && <span>{item.title}</span>}</NavLink>}{nested && expanded && isOpen && <div className="ml-5 mt-1 space-y-0.5 border-l border-[#e4e8f0] pl-3">{item.subItems?.map(sub => <NavLink key={sub.path} to={sub.path} className={({ isActive }) => `app-subnav ${isActive ? 'active' : ''}`}>{sub.title}</NavLink>)}</div>}{nested && !isOpen && hovered === item.title && <div className="fixed left-[72px] z-50 w-60 rounded-lg border border-[#e4e8f0] bg-white p-2 shadow-lg" style={{ top: hoverTop }} onMouseEnter={() => show(item.title)} onMouseLeave={hide}><p className="border-b border-[#edf0f5] px-3 py-2 text-xs font-semibold text-[#18345f]">{item.title}</p>{item.subItems?.map(sub => <NavLink key={sub.path} to={sub.path} className={({ isActive }) => `app-subnav ${isActive ? 'active' : ''}`}>{sub.title}</NavLink>)}</div>}</div>; })}</nav></div></aside>;
};
export default Sidebar;
